version: "3"

services:
  minio:
    container_name: minio
    image: "bitnami/minio:latest"
    volumes:
      - "minio_data:/data"
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET_NAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  file-storage-service:
    container_name: nbf-file-storage-service
    image: nbf-file-storage-service:latest
    ports:
      - "60005:60005"
    volumes:
      - ./config/local.yaml:/app/config/local.yaml:ro
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER}"
      MINIO_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_BUCKET_NAME: "${MINIO_BUCKET_NAME}"
    depends_on:
      - minio
    restart: unless-stopped

volumes:
  minio_data:
