env: "dev"
host: "0.0.0.0"
port: 60005

minio:
  endpoint: "${MINIO_ENDPOINT:localhost:9000}"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  use_ssl: ${MINIO_USE_SSL:false}
  bucket: "${MINIO_BUCKET_NAME:photos}"

presigned_url:
  expiry_hours: 24